# For development only.
# Launch databases used by ccp-equipment-pos with port, password, user, database that match application properties.
# Run: docker-compose up
# Run in background : docker-compose up -d

version: '3.1'

services:

  redis:
    image: redis:latest
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    restart: always