version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: /script/fix_previleges.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /script/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /script/start_server.sh
      timeout: 300
      runas: root
file_exists_behavior: OVERWRITE
