version: v1
server:
  port: 8080
  servlet:
    context-path: /hospital/
    application-display-name: hospital-management

springfox:
  documentation:
    swagger:
      v2:
        path: /doc/v2/api-docs

redis:
  host: 127.0.0.1
  password: password
