version: v1
server:
  port: 8080
  servlet:
    context-path: /hospital/
    application-display-name: hospital-management

springfox:
  documentation:
    swagger:
      v2:
        path: /doc/v2/api-docs

redis:
  host: 127.0.0.1
  port: 6379
  password: password
  index: 0
  ssl: true
  maxtotalconns: 16
  minidleconns: 4
  maxidleconns: 16
  connectiontimeout: 15000
  commandTimeout: 40000
  minEvictableIdleTimeMillis: 60000
  timeBetweenEvictionRunsMillis: 30000
