---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-file
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  application.yml: |
    version: v1
    server:
      max-http-header-size: 20KB
      port: 8080
      servlet:
        context-path: /hospital
        application-display-name: hospital-management

    management:
      health:
        redis:
          enabled: true
    
    redis:
      host: {{ pluck .Values.global.env .Values.redis.host | quote }}
      port: {{ pluck .Values.global.env .Values.redis.port | quote }}
      password: {{ pluck .Values.global.env .Values.redis.password | quote }}
    
