---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-file
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    vault.security.banzaicloud.io/vault-role: "default"
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  application.yml: |
    version: v1
    server:
      max-http-header-size: 20KB
      port: 8080
      servlet:
        context-path: /hospital
        application-display-name: hospital-management

    management:
      endpoints:
        web:
          exposure:
            include: "*"
      health:
        redis:
          enabled: true
    
    redis:
      host: {{ .Values.redis.host }}
      port: {{ .Values.redis.port }}
      password: {{ .Values.redis.password }}
    
    spring:
      redis:
        ssl: true
      kafka:
        consumer:
          bootstrap-servers: my-cluster-kafka-bootstrap.vadal:9092
          group-id: group_id
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer