---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-file
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  application.yml: |
    version: v1
    server:
      port: 8080
      servlet:
        context-path: /hospital
        application-display-name: hospital-management
