---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-file
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  application.yml: |
    version: v1
    server:
      max-http-header-size: 20KB
      port: 8080
      servlet:
        context-path: /hospital
        application-display-name: hospital-management

    management:
      health:
        redis:
          enabled: false
    
    redis:
      host: {{ .Values.redis_host }}
      port: {{ .Values.redis_port }}
      index: {{ .Values.redis_index }}
      password: {{ .Values.redis_password }}
      ssl: {{ .Values.redis_ssl }}
      maxTotalConnections: {{ .Values.redis_maxtotalconns }}
      minIdleConnections: {{ .Values.redis_minidleconns }}
      maxIdleConnections: {{ .Values.redis_maxidleconns }}
      connectionTimeout: {{ .Values.redis_connectiontimeout }}
      commandTimeout: {{ .Values.redis_commandtimeout }}
      minEvictableIdleTimeMillis: {{ .Values.redis_minEvictableIdleTimeMillis }}
      timeBetweenEvictionRunsMillis: {{ .Values.redis_timeBetweenEvictionRunsMillis }}
