apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hospitalms.fullname" . }}
  annotations:
    annotations:
      checksum/config-file: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
      checksum/config-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
      #Kubernetes will notice that the pods have been updated and rollout new pods without downtime.
      timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hospitalms
  template:
    metadata:
      labels:
        app: hospitalms
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            protocol: TCP
            containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /hospital/beds/total
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /hospital/beds/total
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap-env
          volumeMounts:
            - name: {{ .Release.Name }}-configmap-file
              mountPath: /opt/config
      volumes:
        - name: {{ .Release.Name }}-configmap-file
          configMap:
            name: {{ .Release.Name }}-configmap-file
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
