apiVersion: v1
kind: Service
metadata:
  name: {{ include "hospitalms.name" . }}
  labels:
    run: {{include "hospitalms.name" .}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "hospitalms.selectorLabels" . | nindent 4 }}

    
