apiVersion: v1
kind: Service
metadata:
  name: hospitalms
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  nginx_dev_mapping
      prefix: /hospitalms/
      service: hospitalms
spec:
  selector:
    app: hospitalms
  ports:
  - port: 80
    name: hospitalms
    targetPort: http

    
