apiVersion: v1
kind: Service
metadata:
  name: {{ include "hospitalms.name" . }}
  labels:
    run: {{include "hospitalms.name" .}}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  hospitalms_dev_mapping
      prefix: /hospital/
      service: hospitalms:8080
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ include "hospitalms.name" . }}
  selector:
    app: {{ include "hospitalms.name" . }}

    
