apiVersion: v1
kind: Service
metadata:
  name: {{ include "hospitalms.name" . }}
  labels:
    run: {{include "hospitalms.name" .}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "hospitalms.selectorLabels" . }}

    
